export const dashboardHtml=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mail organizer health</title><style>
:root{font:16px system-ui;color:#182b36;background:#f4f6f8}body{max-width:1100px;margin:40px auto;padding:0 24px}h1{font-size:30px;margin-bottom:8px}p{line-height:1.6}.muted{color:#526672}section{background:white;border:1px solid #d7e0e5;border-radius:12px;padding:24px;margin:20px 0}button,input,select{font:inherit;padding:10px 12px;border:1px solid #9eafb8;border-radius:6px;margin:4px}button{cursor:pointer;background:#e9f2f4;color:#143b45}button.primary{background:#146579;color:white}button:disabled{opacity:.5;cursor:default}input{max-width:90%}#token{width:390px}table{width:100%;border-collapse:collapse;text-align:left}th,td{padding:12px;border-bottom:1px solid #e4e9ec;vertical-align:top}th{font-size:13px;color:#526672}code{overflow-wrap:anywhere}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:13px}#status{font-weight:600}#notice{min-height:25px}details{margin:14px 0}label{display:inline-block}h2{font-size:21px}.row{display:flex;gap:12px;flex-wrap:wrap;align-items:center}.pill{padding:8px 14px;background:#eef4f6;border-radius:20px}ul{line-height:1.8}a{color:#146579}.table-scroll{overflow-x:auto}.message{min-width:260px;max-width:470px}.subject{display:block;margin-bottom:6px}.sender,.snippet,.received{font-size:14px;line-height:1.5;overflow-wrap:anywhere}.snippet{margin:8px 0;color:#344e5b}.received{color:#526672}td details{font-size:12px}.actions{min-width:175px}@media(max-width:700px){body{padding:0 12px}section{padding:16px}th,td{padding:10px}}
</style><body><h1>Mail organizer</h1><p class="muted">Health, review and recovery. Message summaries are loaded from Microsoft for this session and are not saved to the organizer’s audit.</p><section id="login"><label>Administration token<br><input id="token" type="password" autocomplete="off" placeholder="Paste your local admin token"></label><button id="connect" class="primary">Connect</button><p class="muted">Kept in this page’s memory only. Closing or refreshing clears it.</p></section><p id="notice" role="status" aria-live="polite"></p><main id="main" hidden><section><div class="row"><h2 id="status">Loading</h2><button id="refresh">Refresh</button><button id="disconnect">Disconnect</button></div><div id="metrics" class="row"></div><ul id="alerts"></ul><p id="scope" class="muted"></p><button id="pause">Pause organizer</button><label>Resume mode <select id="mode"><option value="type-folders">Type folders</option><option value="labels">Labels only</option><option value="observe">Observe only</option><option value="conservative">Conservative</option></select></label><button id="resume">Resume</button></section><section><h2>Review recorded messages</h2><p class="muted">Records describe the last organizer decision, not a live Inbox inventory. Previewing a rerun sends that message to Jev and uses your daily budget. Pause first. Applying a preview changes mail; no action happens merely by selecting a row.</p><p><a href="https://outlook.office365.com/" target="_blank" rel="noopener noreferrer">Open Microsoft 365 work email</a></p><p class="muted">Use your organization’s email address. If Microsoft selects a personal account, choose “Sign in with a different account.” No @outlook.com account is needed. Reading summaries here preserves unread status; opening a message in Outlook follows your Outlook reading settings.</p><div class="table-scroll"><table><thead><tr><th>Message</th><th>Type / state</th><th>Review reason</th><th>Action</th></tr></thead><tbody id="rows"></tbody></table></div><button id="more">Load 20 more records</button></section><section id="preview" hidden><h2>Review preview</h2><p id="previewMessage"></p><pre id="previewText"></pre><button id="apply" class="primary">Apply this preview</button><p class="muted">The preview expires after one hour. A changed message or configuration blocks application. Interrupted operations are reconciled through the durable queue.</p></section></main><script src="/dashboard.js" defer></script></body></html>`;
export const dashboardJs=String.raw`
let token='',cursor='',ticket=null,ticketMessage='',limit=100,working=false;const $=id=>document.getElementById(id);const notice=text=>$('notice').textContent=text;
async function api(path,body){const r=await fetch('/admin/'+path,{cache:'no-store',method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});if(!r.ok)throw Error('Request blocked ('+r.status+'). Check pause state, configuration and credentials.');return r.json();}
const label=s=>String(s??'—').replaceAll('_',' ');
async function health(){const [h,s]=await Promise.all([api('health'),api('status')]);limit=s.dailyLimit;$('mode').value=s.mode;$('status').textContent=label(h.state);$('scope').textContent=h.scope+' · Last scan: '+(h.lastScan?new Date(h.lastScan).toLocaleString():'Not yet');$('metrics').replaceChildren();for(const text of [h.pending+' pending',h.regularBudget.used+' / '+h.regularBudget.limit+' regular attempts today',h.credential.status==='expiry_not_configured'?'Credential expiry not configured':h.credential.daysRemaining+' days until credential expiry']){const span=document.createElement('span');span.className='pill';span.textContent=text;$('metrics').append(span);}$('alerts').replaceChildren();for(const a of h.alerts){const li=document.createElement('li');li.textContent=label(a.code)+(a.count?' ('+a.count+')':'');$('alerts').append(li);}for(const issue of h.unresolvedErrors??[]){const li=document.createElement('li');li.textContent=label(issue.code)+' ('+issue.count+' unresolved records)';$('alerts').append(li);}if(!h.alerts.length){const li=document.createElement('li');li.textContent='No operational alerts.';$('alerts').append(li);}}
function summaryText(d){return [(d.subject||'(No subject)'),[d.senderName,d.senderAddress].filter(Boolean).join(' · '),d.snippet].filter(Boolean).join('\n');}
async function load(reset=false){
 if(reset){cursor='';$('rows').replaceChildren();}
 const page=await api('review?limit=20'+(cursor?'&after='+encodeURIComponent(cursor):''));cursor=page.next;$('more').disabled=!cursor;
 const summaries=[];
 for(const row of page.rows){
  const tr=document.createElement('tr'),message=document.createElement('td');message.className='message';
  const subject=document.createElement('strong');subject.className='subject';subject.textContent='Loading message…';
  const sender=document.createElement('div');sender.className='sender';
  const snippet=document.createElement('p');snippet.className='snippet';
  const received=document.createElement('div');received.className='received';received.textContent=row.receivedAt?new Date(row.receivedAt).toLocaleString():'Prior protected record';
  const details=document.createElement('details'),heading=document.createElement('summary'),id=document.createElement('code');heading.textContent='Record ID';id.textContent=row.id;details.append(heading,id);
  const retry=document.createElement('button');retry.textContent='Retry message summary';retry.hidden=true;
  let context='Record '+row.id;
  const read=async()=>{retry.hidden=true;try{const d=await api('review/message?id='+encodeURIComponent(row.id));subject.textContent=d.subject||'(No subject)';sender.textContent=[d.senderName,d.senderAddress].filter(Boolean).join(' · ')||'Sender unavailable';snippet.textContent=d.snippet||'No text preview available.';context=summaryText(d);}catch{subject.textContent='Message summary unavailable';sender.textContent='The message may have been removed, or Microsoft may be temporarily unavailable.';snippet.textContent='';retry.hidden=false;}};
  retry.onclick=()=>run(read);summaries.push(read);message.append(subject,sender,snippet,received,details,retry);tr.append(message);
  for(const text of [label(row.type)+' / '+label(row.stage),row.reasons.map(label).join(', ')||'No recorded hold']){const td=document.createElement('td');td.textContent=text;td.style.overflowWrap='anywhere';tr.append(td);}
  const td=document.createElement('td');td.className='actions';const select=document.createElement('select');select.setAttribute('aria-label','Review operation');
  for(const op of ['rerun','undo','retry']){const o=document.createElement('option');o.value=op;o.textContent=({rerun:'Reclassify',undo:'Undo last change',retry:'Retry failed job'})[op];select.append(o);}
  const button=document.createElement('button');button.textContent='Preview';button.onclick=()=>run(async()=>{ticket=await api('review/preview',{id:row.id,operation:select.value,requestId:crypto.randomUUID()});ticketMessage=context;showTicket();await health();});
  const open=document.createElement('button');open.textContent='Open message in Outlook';open.onclick=()=>{if(working)return;const win=window.open('about:blank','_blank');if(win)win.opener=null;run(async()=>{try{const link=await api('review/open?id='+encodeURIComponent(row.id));if(win)win.location=link.url;else throw Error('Allow popups to open Outlook, or use the Microsoft 365 work email link above.');}catch(e){if(win)win.close();throw e;}});};
  td.append(open,select,button);tr.append(td);$('rows').append(tr);
 }
 // Bound Microsoft reads to three at a time and twenty per page. Never persist content.
 let next=0;await Promise.all(Array.from({length:Math.min(3,summaries.length)},async()=>{while(next<summaries.length)await summaries[next++]();}));
}
function showTicket(){$('preview').hidden=false;$('previewMessage').textContent=ticketMessage;const p=ticket.proposal?.plan;$('previewText').textContent=[({rerun:'Reclassify this message',undo:'Undo the last organizer change',retry:'Retry this failed classification'})[ticket.operation], 'Status: '+label(ticket.state),ticket.error?'Reason: '+label(ticket.error):'', 'Destination: '+(p?.destination?.displayName??(ticket.operation==='retry'?'Queue for processing after you resume':'Keep in current folder')),p?'Labels: '+(p.finalCategories.join(', ')||'None'):'','Expires: '+new Date(ticket.expiresAt).toLocaleString()].filter(Boolean).join('\n');$('apply').disabled=ticket.state!=='ready';$('preview').scrollIntoView({behavior:'smooth'});}
async function run(fn){if(working)return;working=true;for(const b of document.querySelectorAll('button'))b.disabled=true;try{await fn();notice('Updated.');}catch(e){notice(e.message);}finally{working=false;for(const b of document.querySelectorAll('button'))b.disabled=false;$('more').disabled=!cursor;$('apply').disabled=!ticket||ticket.state!=='ready';}}
$('connect').onclick=()=>run(async()=>{token=$('token').value;$('token').value='';await health();$('login').hidden=true;$('main').hidden=false;await load(true);});$('disconnect').onclick=()=>{token='';ticket=null;location.reload();};$('refresh').onclick=()=>run(async()=>{await health();await load(true);});$('more').onclick=()=>run(()=>load());$('pause').onclick=()=>run(async()=>{await api('pause',{});await health();});$('resume').onclick=()=>run(async()=>{await api('resume',{mode:$('mode').value,dailyLimit:limit});await health();});$('apply').onclick=()=>run(async()=>{ticket=await api('review/apply',{ticketId:ticket.id});showTicket();await health();await load(true);});
setInterval(()=>{if(token&&!working)health().catch(()=>notice('Health refresh failed. Check connection or refresh your session.'));},30000);
`;
export function dashboardResponse(path:string){return new Response(path==='/dashboard'?dashboardHtml:dashboardJs,{headers:{'Content-Type':path==='/dashboard'?'text/html; charset=utf-8':'text/javascript; charset=utf-8','Cache-Control':'no-store','Content-Security-Policy':"default-src 'none'; script-src 'self'; style-src 'unsafe-inline'; connect-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'",'Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff'}});}
